### ISSUE TITLE
Extra "Region" column in IC table

### ISSUE THREAD

**Issue by dkulp2** [broadinstitute/dropviz#71]
Where did that come from?

**Comment by dkulp2** [comment]
@arpiar the IC table has two column headings called "Region". One corresponds to the tissue/region (Cerebellum, Frontal Cortex, etc.) The other corresponds to a heading called anatomical_region in the original table (Supramammillary Nucleus (SuM), SN/VTA (SNr), etc.)
What would you like the headings to be in the app?

**Comment by arpiar** [comment]
anatomical_region could be "anatomical_guess"  or "anatomical_notes" ?

**Comment by dkulp2** [comment]
I'm noticing that there are notes in the IC tables for
hypothesized_common_name and anatomical_region that say things like "CHECK
ME" and "xxx". Is this something that you want to update over time?
