### ISSUE TITLE
 No cell names (colnames) names present in the input matrix

### ISSUE THREAD

**Issue by chenx9** [broadinstitute/dropviz#77]
when   I wanted creat a seurat object after loading dge file,I get the error:
Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features,  : 
  No cell names (colnames) names present in the input matrix

the martrix read in R don't have the dimnames(rownames and colnames),what should I do？OR How can I get it?

**Comment by alecw** [comment]
Hi chenx9,

Are you sure you are posting this issue in the correct repository?  I don't think this code does anything seurat-related.

Regards, Alec
